### ISSUE TITLE
Editing the allergy of an individual deletes all existing allergies

### ISSUE THREAD

**Issue by rahula1008** [rahula1008/pe#7]
<i><video controls><source src="https://raw.githubusercontent.com/rahula1008/pe/main/files/6e545eb5-a319-4977-a9b3-88f901c88b4d.mov" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/rahula1008/pe/main/files/6e545eb5-a319-4977-a9b3-88f901c88b4d.mov</i>

Currently, if you want to modify a patient's allergy, and you use  the edit command for instance in the video above, it will delete all existing allergies. There is nothing about this mentioned in the user guide, and as such, if an unsuspecting doctor/nurse wants to add a recently discovered allergy to a patient, they may accidentally delete all the previous ones. Now in the rare case that they did not memorise the previous allergies and they don't have another record of the patient, they may have to go through the hassle of contacting the patient again. (Of course, if they have other records of the patient, it is not an issue as they can simply retype everything, but then again, if they have another record why would they be using this app).

In addition to this, wouldn't it just be more convenient for users(doctors) to be able to modify the tag they wish without having to retype everything? For instance, if a patient has three allergies: peanuts, mushrooms, and shellfish.

If they then realise that actually, a patient is not allergic to all shellfish, but just prawns, wouldn't it be good to be able to modify that 3rd allergy without deleting / having to retype the first two allergies?

**Comment by juhabae** [comment]
Hello, we are computer science students interested in contributing to this project. We came across this issue and believe it is a meaningful enhancement to the user experience. 

We would like to work on resolving this issue. Could we take this on?

Thank you!
